//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesagge
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int SendId { get; set; }
        public int AcceptId { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
