//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRM_SYSTEMEntities : DbContext
    {
        public CRM_SYSTEMEntities()
            : base("name=CRM_SYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Transaction> C_Transaction { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Balan> Balans { get; set; }
        public virtual DbSet<Bonservice> Bonservices { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_to_Serviceds> Customer_to_Serviceds { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Jobpost> Jobposts { get; set; }
        public virtual DbSet<JobsApplication> JobsApplications { get; set; }
        public virtual DbSet<Mesagge> Mesagges { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<Stoct> Stocts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
